--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

return function(Table)
  Table("xenin_framework_settings", function(tbl)
    tbl:string("id", 255):primary()
    tbl:text("value")
    tbl:boolean("json"):nullable()
    tbl:integer("server_id"):nullable()
  end)
end
