--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local PANEL = {}

XeninUI:CreateFont("Xenin.Configurator.Admin.Title", 32)
XeninUI:CreateFont("Xenin.Configurator.Admin.Subtitle", 14)

function PANEL:Init()
  self.CloseBtn = self:Add("DButton")
  self.CloseBtn:Dock(RIGHT)
  self.CloseBtn:SetText("")
  self.CloseBtn.CloseButton = Color(100, 100, 100)
  self.CloseBtn.Alpha = 0
  self.CloseBtn.DoClick = function(pnl)
    self:GetParent():Remove()
  end
  self.CloseBtn.Paint = function(pnl, w, h)
    draw.RoundedBox(h / 2, 0, 0, w, h, ColorAlpha(XeninUI.Theme.Red, pnl.Alpha))

    surface.SetDrawColor(pnl.CloseButton)
    surface.SetMaterial(XeninUI.Materials.CloseButton)
    surface.DrawTexturedRect(12, 12, w - 24, h - 24)
  end
  self.CloseBtn.OnCursorEntered = function(pnl)
    pnl:Lerp("Alpha", 255)
    pnl:LerpColor("CloseButton", Color(255, 255, 255))
  end
  self.CloseBtn.OnCursorExited = function(pnl)
    pnl:Lerp("Alpha", 0)
    pnl:LerpColor("CloseButton", Color(100, 100, 100))
  end

  self.Name = self:Add("DPanel")
  self.Name:Dock(LEFT)
  self.Name.Paint = function(pnl, w, h)
    XeninUI:DualText({
      self.Text[1],
      "Xenin.Configurator.Admin.Title",
      color_white,
      TEXT_ALIGN_LEFT,
      2,
      150
    }, {
      self.Text[2],
      "Xenin.Configurator.Admin.Subtitle",
      Color(145, 145, 145),
      TEXT_ALIGN_LEFT,
      0,
      0
    }, 0, -2, w, h)
  end

  self.Search = self:Add("Xenin.Configurator.Admin.SearchBar")
  self.Search:Dock(FILL)
  self.Search:DockMargin(8, 0, 250, 0)
  self.Search:SetPlaceholder("Search for anything")
  self.Search:SetIcon(XeninUI.Materials.Search, true)
  self.Search:SetVisible(false)
end

function PANEL:SetText(text)
  self.Text = text
end

function PANEL:PerformLayout(w, h)
  self.CloseBtn:SetWide(h)
  self.Name:SetWide(200)
end

vgui.Register("Xenin.Configurator.Admin.Top", PANEL)
