--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

local yellow = Color(201, 176, 15)
local red = Color(230, 58, 64)
local green = Color(46, 204, 113)

function XeninUI:InvokeSQL(conn, str, name, successFunc, errFunc, returnId)
  local p = XeninUI.Promises.new()
  local debug = self.Debug
  local sqlStr = conn.isMySQL() and "[MySQL] " or "[SQLite] "
  local successDetour = function(result)
    if debug then
      MsgC(yellow, sqlStr, color_white, name, green, " Success!\n")
    end
  end
  local _successFunc = function(result, id)
    successDetour(result, id)
    if returnId then
      p:resolve({
        result,
        id
      })
    else
      p:resolve(result)
    end
  end
  local errDetour = function(err)
    if debug then
      MsgC(yellow, sqlStr, color_white, name, red, " Failure! ", color_white, err .. "\n")
    end
  end
  local _errFunc = function(err)
    errDetour(err)
    p:reject(err)
  end

  conn.query(str, _successFunc, _errFunc)

  return p
end
