--[[
This code was generated by LAUX, a Lua transpiler
LAUX is a fork of LAU with additional changes.

More info & source code can be found at: https://gitlab.com/sleeppyy/laux
]]

util.AddNetworkString("XeninUI.Notification")

function XeninUI:Notify(ply, str, icon, duration, progressColor, textColor, markup)
  net.Start("XeninUI.Notification")
  net.WriteTable({
    str = str,
    icon = icon,
    dur = duration,
    progressCol = progressColor,
    textCol = textColor,
    markup = markup
  })
  net.Send(ply)
end
